config/routes.rb
Shm::Application.routes.draw do
  root :to => 'index#index'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match '/error/500', :to => 'error#render_error'
  match '/error/404', :to => 'error#render_not_found'
  match '/error/403', :to => 'error#render_access_denied'

  resources :bid, :block
  resources :user, :path_names => {:show => :profile}

  match '/doctor(/:path)', :to => redirect { |params, request| "/cabinet/doctor/#{params[:path]}" }
  match '/patient(/:path)', :to => redirect { |params, request| "/cabinet/patient/#{params[:path]}" }
  match '/admin(/:path)', :to => redirect { |params, request| "/cabinet/admin/#{params[:path]}" }
  match '/manager(/:path)', :to => redirect { |params, request| "/cabinet/manager/#{params[:path]}" }

  match '/assets/rails' => 'environment#rails'

  namespace :cabinet do
    namespace :doctor do
      root :to => 'index#index'
      match '/' => 'index#index'

      resources :appointments, :controller => 'appointment'
      resources :documents, :controller => 'document'
      resources :patient, :parameter, :user, :diagnostic

      match 'diagnostic/chart' => 'diagnostic#chart', :via => :post
      match 'diagnostic/raw' => 'diagnostic#raw', :via => :post

      match 'link/parameter/:parameter_id/to/:patient_id' => 'parameter#link', :via => :post
      match 'unlink/parameter/:parameter_id/from/:patient_id' => 'parameter#unlink', :via => :post
      
      match 'user/find' => 'user#find', :via => :post
      match 'user/find_doctor' => 'user#find_doctor', :via => :post
      match 'user/find_for_set' => 'user#find_for_set', :via => :post

      match 'appointment/confirm' => 'appointment#confirm', :via => :post
      match 'appointment/me/(:id)' => 'appointment#index', :via => :get
      match 'appointments/for/(:id)' => 'appointment#get_free_appointments_for'
      match 'appointment/new/get_form' => 'appointment#get_patient_searching_form'
      match 'appointment/new/get_form2' => 'appointment#searching_form_for_appt_assig'
      match 'appointment/new' => 'appointment#new_appointment'

      match 'appointment/colleague/(:id)' => 'user#index', :via => :get
      match 'appointment/start_appointment/(:id)' => 'appointment#start_appointment', via: :get
      match 'appointment/stop_appointment/(:id)' => 'appointment#stop_appointment', via: :get
      match 'users/doctors' => 'user#get_doctors'

      match 'diagnoses/find-by-name' => 'patient#find_diagnose', :via => :post
      match 'diagnoses/confirm' => 'patient#confirm_diagnoses', :via => :post

      match 'diagnoses/patient/(:id)' => 'patient#all_diagnoses'
      match 'diagnoses/get-form/patient/(:id)' => 'patient#diagnoses_assigning'

      match 'medicament/find' => 'patient#find_medicament', :via => :post
      match 'medicament/confirm' => 'patient#confirm_medicaments'

      match 'document/form/(:id)' => 'document#get_form_body'

    end
    namespace :patient do
      root :to => 'index#index'
      match '/' => 'index#index'

      match '/doctor/find' => 'doctor#find'
      match '/appointment/find' => 'appointment#find'
      match '/event/unsubscribe/:id' => 'event#unsubscribe'

      resources :calendar, :event, :doctor, :appointment, :parameter, :document
    end
    namespace :admin do
      root :to => 'index#index'
      match '/' => 'index#index'
    end
    namespace :manager do
      root :to => 'index#index'
      match '/' => 'index#index'

      resources :parameter, :bid, :event, :user, :rule_parameter_input

      match '/event/find' => 'event#find', :via => :post
      match '/event/find_attendee' => 'event#find_attendee', :via => :post
      match '/event/json' => 'event#json_format', :via => :post

      match '/rule/new' => 'recurrence#new', :via => :get
      match '/rule/find' => 'recurrence#find', :via => :post
      match '/rule/edit/:id' => 'recurrence#edit', :via => :get

      match '/user/find' => 'user#find', :via => :post
    end
  end

  scope :diagnostic do
    match '/parameter' => 'diagnostic#parameter', :via => :post
  end

  match ':controller(/:action(/:id))(.:format)'

  if ::Rails.application.config.handle_errors
    match '*path', :to => redirect { |params, request| "/error/404?from=#{request.url}" }
  end
end

app/models/manager.rb
class Manager < User
  default_scope :joins => :roles
  default_scope where("roles.name = 'manager'")
  default_scope :readonly => false
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  has_many :parameters_to_patientses, :class_name => ParametersToPatients
  # Пациенты которым назначен данный параметр
  has_many :patient_users, :through => :parameters_to_patientses, :foreign_key => :user_id
  # Введенные значения для параметра
  has_many :parameters_datas
  # Правило ввода параметра
  belongs_to :rule_parameter_input

  attr_accessible :type, :name, :metadata, :rule_parameter_input, :rule_parameter_input_id
  attr_accessor :metadata
  before_save :merge_with_default_metadata
  after_initialize :merge_with_default_metadata
  validate :validate_metadata_structure
  validates :name, :presence => true
  validates :rule_parameter_input_id, :presence => true

  # Метаданные параметра по-умолчанию
  def default_metadata ; {} end
  # Метод для валидации структуры метаданных
  def metadata_validator ; {} end
  # Метод для валидации значения параметра
  def validate_value value ; false end

  def metadata= value
    write_attribute(:metadata, default_metadata.merge(value).to_json)
  end

  def metadata
    read_attribute(:metadata) ?
            default_metadata.merge(JSON.parse(read_attribute(:metadata), {:symbolize_names => true}).to_hash) : default_metadata
  end

  private

  # Слияние дефолтных метаданных с указанными
  def merge_with_default_metadata
    write_attribute(:metadata, default_metadata.merge(
        read_attribute(:metadata) ?
            JSON.parse(read_attribute(:metadata), {:symbolize_names => true}).to_hash : {}).to_json)
  end

  # Проверка структуру метаданных
  def validate_metadata_structure
    validate_hashes metadata_validator, metadata
  end

  # Валидация структуры хэш-таблицы на основе другой хэш-таблицы
  def validate_hashes validator_hash, validated_hash
    validated_hash.each do |k, v|
      if k[0] != '_'
        if validator_hash.include?(k)
          validator = validator_hash[k]
          errors.add(:metadata, validator[:_error_message]) unless validator[:_validate].call(v)
          validate_hashes validator_hash[k], v if v.is_a? Hash
        else
          errors.add(:metadata, 'parameter.errors.metadata.not_defined_key')
        end
      else
        errors.add(:metadata, 'parameter.errors.metadata.invalid_key')
      end
    end
  end
end

app/models/parameter/bool_parameter.rb
class BoolParameter < Parameter
  def default_metadata
    {
        :values => %w(true false),
        :default => 'false'
    }
  end

  def metadata_validator
    {
        :default => {
            :_validate => lambda { |v| default_metadata.values.include? v },
            :_error_message => 'parameter.bool.metadata.errors.default'
        },
        :values => {
            :_validate => lambda { |v| v == %w(true false) },
            :_error_message => 'parameter.bool.metadata.errors.values'
        }
    }
  end

  def validate_value value
    metadata[:values].include? value.to_s
  end
end

app/models/parameter/integer_parameter.rb
class IntegerParameter < Parameter
  def default_metadata
    {
        :default => nil,
        :validators => {
            :min => nil,
            :max => nil
        }
    }
  end

  def metadata_validator
    {
        :default => {
            :_validate => lambda { |v| Integer(v) rescue false },
            :_error_message => 'parameter.integer.metadata.errors.default'
        },
        :validators => {
            :_validate => lambda { |v| v.is_a? Hash },
            :_error_message => 'parameter.integer.metadata.errors.validators',
            :min => {
                :_validate => lambda { |v| Integer(v) rescue false },
                :_error_message => 'parameter.integer.metadata.errors.validators.min'
            },
            :max => {
                :_validate => lambda { |v| Integer(v) rescue false },
                :_error_message => 'parameter.integer.metadata.errors.validators.max'
            }
        }
    }
  end

  def validate_value value
    if (value.to_s =~ /^[-+]?[0-9]+$/).nil?
      false
    else
      value.to_i.between? metadata[:validators][:min].to_i, metadata[:validators][:max].to_i
    end
  end
end

app/models/parameter/select_parameter.rb
class SelectParameter < Parameter
  def default_metadata
    {
        :default => nil,
        :values => []
    }
  end

  def metadata_validator
    {
        :default => {
            :_validate => lambda { |v| true },
            :_error_message => 'parameter.select.metadata.errors.default'
        },
        :values => {
            :_validate => lambda { |v| v.is_a? Array and v.length > 0 },
            :_error_message => 'parameter.select.metadata.errors.values'
        }
    }
  end

  def validate_value value
    metadata[:values].include? value.to_s
  end
end

app/models/parameter/string_parameter.rb
class StringParameter < Parameter
  def default_metadata
    {
        :default => ''
    }
  end

  def metadata_validator
    {
        :default => {
            :_validate => lambda { |v| true },
            :_error_message => 'parameter.string.metadata.errors.default'
        }
    }
  end

  def validate_value value ; true end
end

app/controllers/cabinet/doctor/parameter_controller.rb
class Cabinet::Doctor::ParameterController < Cabinet::DoctorController
  def link
    l = ParametersToPatients.new({:user_id => params[:patient_id], :parameter_id => params[:parameter_id]})
    respond_to do |f|
      if l.save
        f.json { render :json => {
            :message => 'parameter.link'
        } }
      else
        f.json { render :json => {
            :message => 'parameter.link.error',
            :errors => l.errors.messages
        }, :status => :unprocessable_entity }
      end
    end
  end

  def unlink
    l = ParametersToPatients.where(:user_id => params[:patient_id]).where(:parameter_id => params[:parameter_id]).first
    respond_to do |f|
      if l.destroy.destroyed?
        f.json { render :json => {
            :message => 'parameter.unlink'
        } }
      else
        f.json { render :json => {
            :message => 'parameter.unlink.error',
            :errors => l.errors.messages
        }, :status => :unprocessable_entity }
      end
    end
  end

end

app/controllers/cabinet/manager/bid_controller.rb
class Cabinet::Manager::BidController < Cabinet::ManagerController
  layout 'cabinet/manager/layout'

  def index
    @bids = Bid.limit(20)
  end

  def show
    @bid = Bid.find params[:id]
  end

  def approve
    @bid = Bid.find params[:id]

    respond_to do |f|
      if @bid.approve
        f.html { redirect_to({:action => :show, :id => @bid.id}, :notice => 'bid_approved') }
      else
        raise Exception
      end
    end
  end

  def reject
    @bid = Bid.find params[:id]

    respond_to do |f|
      if @bid.reject
        f.html { redirect_to({:action => :show, :id => @bid.id}, :notice => 'bid_rejected') }
      else
        raise Exception
      end
    end
  end
end

app/controllers/cabinet/manager/calendar_controller.rb
class Cabinet::Manager::CalendarController < Cabinet::ManagerController
  layout 'cabinet/manager/layout'

  def index
  end

  def show
    @user = User.find params[:id]
    gon.id = params[:id]
  end
end

app/controllers/cabinet/manager/event_controller.rb
class Cabinet::Manager::EventController < Cabinet::ManagerController
  def index
    start_date = Time.at(params[:start].to_i).to_date
    end_date = Time.at(params[:end].to_i).to_date
    user_id = params[:id]

    respond_to do |f|
      f.html
      f.json {
        events = Event.find_by_user_and_date user_id, start_date, end_date
        render :json => events.map {|e|{
            id:    e.id,
            title: t("event.categories.#{e.type.underscore.gsub('_event', '')}"),
            className: e.status_to_css,
            start: e.date_start,
            end:   e.date_end
        }}
      }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = params[:event][:type].constantize.new params[:event]

    respond_to do |f|
      if @event.save!
        f.html { redirect_to({:action => :show, :id => @event.id}, :notice => 'event_created') }
      else
        f.html { render :action => :new }
      end
    end
  end

  def find
    @calendars = Calendar.where('name like ?', "%#{params[:name]}%").limit(10)

    render :layout => false
  end

  def find_attendee
    @users = User.where('email like ?', "%#{params[:name]}%").limit(10)

    render :layout => false
  end

  def show
    @event = Event.find params[:id]

    respond_to do |format|
      format.html
      format.json { render :json => @event }
    end
  end
end

app/controllers/cabinet/manager/index_controller.rb
class Cabinet::Manager::IndexController < Cabinet::ManagerController

  def index
  end

end

app/controllers/cabinet/manager/parameter_controller.rb
class Cabinet::Manager::ParameterController < Cabinet::ManagerController
  def index
    @parameters = Parameter.order('id DESC').limit(20)
  end

  def new
  end

  def create
    @parameter = params[:parameter][:type].constantize.new params[:parameter]
    respond_to do |f|
      if @parameter.save
        f.html { redirect_to({:action => :index}, :notice => 'Parameter created.') }
      else
        f.html { render :action => :new }
      end
    end
  end

  def edit
    @parameter = Parameter.find params[:id]
  end

  def update
    @parameter = Parameter.find params[:id]
    respond_to do |f|
      if @parameter.update_attributes params[:parameter]
        f.html { redirect_to({:action => :index}, :notice => 'Parameter updated.') }
      else
        f.html { render :action => :edit }
      end
    end
  end

  def destroy
    @parameter = Parameter.find params[:id]
    @parameter.destroy

    respond_to do |f|
      f.html { redirect_to :action => :index }
    end
  end
end

app/controllers/cabinet/manager/recurrence_controller.rb
class Cabinet::Manager::RecurrenceController < Cabinet::ManagerController

  layout 'cabinet/manager/layout'

  def new
    if request.post?
      rule = RecurrenceRule.new params[:rule]
      rule.save!

      redirect_to :controller => :recurrence, :action => :new
    end
  end

  def find
    @events = Event.where('summary like ?', "%#{params[:name]}%").limit(10)

    render :layout => false
  end

  def show
    @rule = RecurrenceRule.find params[:id]
  end

  def edit
    @rule = RecurrenceRule.find params[:id]
  end
end

app/controllers/cabinet/manager/rule_parameter_input_controller.rb
class Cabinet::Manager::RuleParameterInputController < Cabinet::ManagerController
  def index
    @rules = RuleParameterInput.all
  end
end

app/controllers/cabinet/manager/schedule_controller.rb
class Cabinet::Manager::ScheduleController < Cabinet::ManagerController
  def index
    @doctor = DoctorUser.find params[:id]
  end
end

app/controllers/cabinet/manager/user_controller.rb
class Cabinet::Manager::UserController < Cabinet::ManagerController

  layout 'cabinet/manager/layout'

  def index

  end

  def find
    @users = User.select([:id, :email]).where('email like ?', "%#{params[:name]}%").limit(200)

    respond_to do |f|
      f.html { render :layout => false }
      f.json { render :json => @users }
    end
  end

  def show
    @user = User.find params[:id]
  end
end

app/controllers/cabinet/manager_controller.rb
class Cabinet::ManagerController < ApplicationController
  layout 'cabinet/manager/layout'

  before_filter :_authorize

  private
  def _authorize
    authorize! :access, :manager_cabinet
  end
end

app/controllers/cabinet/patient/parameter_controller.rb
class Cabinet::Patient::ParameterController < Cabinet::PatientController
  def index
    @parameters = User.current.parameters
  end

  def create
    @storage = ParametersData.new params[:storage]
    @storage.user_id = current_user.id
    respond_to do |f|
      if @storage.save
        f.json { render :json => {
            :message => 'parameter_data.saved'
        } }
      else
        f.json { render :json => {
            :message => 'parameter_data.saved.error',
            :errors => @storage.errors.messages
        }, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/cabinet/doctor/parameter_helper.rb
module Cabinet::Doctor::ParameterHelper
end

app/helpers/cabinet/manager/bid_helper.rb
module Cabinet::Manager::BidHelper
  def user_bid_path bid
    url_for :controller => :'cabinet/manager/user', :action => :show, :id => PatientUser.find_by_email(bid.email).id
  end
end

app/views/cabinet/manager/parameter/_bool_parameter.html.erb
<%= simple_form_for p, :as => :parameter, :url => url_for(:controller => :parameter, :action => p.new_record? ? :create : :update), :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.hidden_field :type, :value => 'BoolParameter' %>
    <%= f.input :name, :input_html => {:placeholder => 'parameter name'} %>
    <div class="control-group">
      <label class="control-label">Default</label>

      <div class="controls">
        <%= check_box_tag 'parameter[metadata][default]', 'true', p.metadata[:default] == 'true' %>
      </div>
    </div>
    <%= f.input :rule_parameter_input_id, :collection => RuleParameterInput.all, :value_method => :id, :label_method => :rule %>
    <div class="form-actions">
      <%= link_to 'Back', {:controller => :parameter, :action => :index}, :class => 'btn' %>
      <button type="submit" class="btn btn-success">
        <%= p.new_record? ? 'Create' : 'Update' %>
      </button>
    </div>
<% end %>

app/views/cabinet/manager/parameter/_errors.html.erb
<% if parameter.errors.present? %>
    <% parameter.errors.each do |e, m| %>
        <div class="alert alert-error">
          <button class="close" data-dismiss="alert">&times;</button>
          <strong><%= t m %></strong>
        </div>
    <% end %>
<% end %>

app/views/cabinet/manager/parameter/_integer_parameter.html.erb
<%= simple_form_for p, :as => :parameter, :url => url_for(:controller => :parameter, :action => p.new_record? ? :create : :update), :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.hidden_field :type, :value => 'IntegerParameter' %>
    <%= f.input :name, :input_html => {:placeholder => 'parameter name'} %>
    <div class="control-group">
      <label class="control-label">Default</label>

      <div class="controls">
        <input type="text" name="parameter[metadata][default]" placeholder="default value" value="<%= p.metadata[:default] %>">
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Min</label>

      <div class="controls">
        <input type="text" name="parameter[metadata][validators][min]" placeholder="min value for parameter" value="<%= p.metadata[:validators][:min] %>">
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Max</label>

      <div class="controls">
        <input type="text" name="parameter[metadata][validators][max]" placeholder="max value for parameter" value="<%= p.metadata[:validators][:max] %>">
      </div>
    </div>
    <%= f.input :rule_parameter_input_id, :collection => RuleParameterInput.all, :value_method => :id, :label_method => :rule %>
    <div class="form-actions">
      <%= link_to 'Back', {:controller => :parameter, :action => :index}, :class => 'btn' %>
      <button type="submit" class="btn btn-success">
        <%= p.new_record? ? 'Create' : 'Update' %>
      </button>
    </div>
<% end %>

app/views/cabinet/manager/parameter/_select_parameter.html.erb
<%= simple_form_for p, :as => :parameter, :url => url_for(:controller => :parameter, :action => p.new_record? ? :create : :update), :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.hidden_field :type, :value => 'SelectParameter' %>
    <%= f.input :name, :input_html => {:placeholder => 'parameter name'} %>
    <div class="control-group">
      <label class="control-label">Values</label>

      <div class="controls">
        <div class="input-append">
          <input type="text" placeholder="enter new value">
          <button type="button" class="btn" id="select-p-add-new-value-button">Add</button>
        </div>
      </div>
    </div>
    <div class="control-group">
      <div id="select-p-values-box">
        <% p.metadata[:values].each do |v| %>
            <div class="alert alert-info">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <input type="hidden" name="parameter[metadata][values][]" value="<%= v %>">
              <label class="as-default radio">
                <%= radio_button_tag 'parameter[metadata][default]', v, v == p.metadata[:default] %>
                <%= v %>
              </label>
            </div>
        <% end %>
      </div>
    </div>
    <%= f.input :rule_parameter_input_id, :collection => RuleParameterInput.all, :value_method => :id, :label_method => :rule %>
    <div class="form-actions">
      <%= link_to 'Back', {:controller => :parameter, :action => :index}, :class => 'btn' %>
      <button type="submit" class="btn btn-success">
        <%= p.new_record? ? 'Create' : 'Update' %>
      </button>
    </div>
<% end %>

app/views/cabinet/manager/parameter/_string_parameter.html.erb
<%= simple_form_for p, :as => :parameter, :url => url_for(:controller => :parameter, :action => p.new_record? ? :create : :update), :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.hidden_field :type, :value => 'StringParameter' %>
    <%= f.input :name, :input_html => {:placeholder => 'parameter name'} %>
    <div class="control-group">
      <label class="control-label">Default</label>

      <div class="controls">
        <input type="text" name="parameter[metadata][default]" placeholder="default value" value="<%= p.metadata['default'] %>">
      </div>
    </div>
    <%= f.input :rule_parameter_input_id, :collection => RuleParameterInput.all, :value_method => :id, :label_method => :rule %>
    <div class="form-actions">
      <%= link_to 'Back', {:controller => :parameter, :action => :index}, :class => 'btn' %>
      <button type="submit" class="btn btn-success">
        <%= p.new_record? ? 'Create' : 'Update' %>
      </button>
    </div>
<% end %>

app/views/cabinet/manager/parameter/edit.html.erb
<h3>Edit <%= @parameter.type.gsub('Parameter', '').downcase %> parameter</h3>
<%= render :partial => 'errors', :locals => {:parameter => @parameter} %>
<%= render :partial => @parameter.type.underscore, :locals => {:p => @parameter} %>

app/views/cabinet/manager/parameter/index.html.erb
<h3>Parameters</h3>
<table class="table">
  <% @parameters.each do |p| %>
      <tr>
        <td>
          <%= link_to 'Edit', edit_cabinet_manager_parameter_path(p), :class => 'btn pull-right parameter-edit' %>
          <%= link_to 'Delete', cabinet_manager_parameter_path(p), :confirm => 'Are you sure you want to destroy parameter?', :method => :delete, :class => 'btn btn-danger pull-right' %>
          <div style="margin: 8px 8px 0 0">
              <div class="label label-info pull-right"><%= p.class.name.gsub('Parameter', '').downcase %></div>
              <div class="label label-important pull-right"><%= p.rule_parameter_input.rule %></div>
          </div>
          <%= p.name %>
        </td>
      </tr>
  <% end %>
</table>

app/views/cabinet/manager/parameter/new.html.erb
<h3>Create new parameter</h3>
<ul class="nav nav-tabs">
  <li><a>Select parameter type:</a></li>
  <% [StringParameter, IntegerParameter, SelectParameter, BoolParameter].each_with_index do |t, i| %>
      <li <% if @parameter.is_a?(t) || (i == 0 && !@parameter.present?) %> class="active" <% end %>><a href="#<%= t.name.underscore %>" data-toggle="tab"><%= t t %></a></li>
  <% end %>
</ul>
<div class="tab-content">
  <% [StringParameter, IntegerParameter, SelectParameter, BoolParameter].each_with_index do |t, i| %>
      <div class="tab-pane <% if @parameter.is_a?(t) || (i == 0 && !@parameter.present?) %> active <% end %>" id="<%= t.name.underscore %>">
        <% if @parameter.present? && @parameter.is_a?(t) %>
            <%= render :partial => 'errors', :locals => {:parameter => @parameter} %>
            <%= render :partial => t.name.underscore, :locals => {:p => @parameter} %>
        <% else %>
            <%= render :partial => t.name.underscore, :locals => {:p => t.new} %>
        <% end %>
      </div>
  <% end %>
</div>