config/routes.rb
Shm::Application.routes.draw do
  root :to => 'index#index'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match '/error/500', :to => 'error#render_error'
  match '/error/404', :to => 'error#render_not_found'
  match '/error/403', :to => 'error#render_access_denied'

  resources :bid, :block
  resources :user, :path_names => {:show => :profile}

  match '/doctor(/:path)', :to => redirect { |params, request| "/cabinet/doctor/#{params[:path]}" }
  match '/patient(/:path)', :to => redirect { |params, request| "/cabinet/patient/#{params[:path]}" }
  match '/admin(/:path)', :to => redirect { |params, request| "/cabinet/admin/#{params[:path]}" }
  match '/manager(/:path)', :to => redirect { |params, request| "/cabinet/manager/#{params[:path]}" }

  match '/assets/rails' => 'environment#rails'

  namespace :cabinet do
    namespace :doctor do
      root :to => 'index#index'
      match '/' => 'index#index'

      resources :appointments, :controller => 'appointment'
      resources :documents, :controller => 'document'
      resources :patient, :parameter, :user, :diagnostic

      match 'diagnostic/chart' => 'diagnostic#chart', :via => :post
      match 'diagnostic/raw' => 'diagnostic#raw', :via => :post

      match 'link/parameter/:parameter_id/to/:patient_id' => 'parameter#link', :via => :post
      match 'unlink/parameter/:parameter_id/from/:patient_id' => 'parameter#unlink', :via => :post
      
      match 'user/find' => 'user#find', :via => :post
      match 'user/find_doctor' => 'user#find_doctor', :via => :post
      match 'user/find_for_set' => 'user#find_for_set', :via => :post

      match 'appointment/confirm' => 'appointment#confirm', :via => :post
      match 'appointment/me/(:id)' => 'appointment#index', :via => :get
      match 'appointments/for/(:id)' => 'appointment#get_free_appointments_for'
      match 'appointment/new/get_form' => 'appointment#get_patient_searching_form'
      match 'appointment/new/get_form2' => 'appointment#searching_form_for_appt_assig'
      match 'appointment/new' => 'appointment#new_appointment'

      match 'appointment/colleague/(:id)' => 'user#index', :via => :get
      match 'appointment/start_appointment/(:id)' => 'appointment#start_appointment', via: :get
      match 'appointment/stop_appointment/(:id)' => 'appointment#stop_appointment', via: :get
      match 'users/doctors' => 'user#get_doctors'

      match 'diagnoses/find-by-name' => 'patient#find_diagnose', :via => :post
      match 'diagnoses/confirm' => 'patient#confirm_diagnoses', :via => :post

      match 'diagnoses/patient/(:id)' => 'patient#all_diagnoses'
      match 'diagnoses/get-form/patient/(:id)' => 'patient#diagnoses_assigning'

      match 'medicament/find' => 'patient#find_medicament', :via => :post
      match 'medicament/confirm' => 'patient#confirm_medicaments'

      match 'document/form/(:id)' => 'document#get_form_body'

    end
    namespace :patient do
      root :to => 'index#index'
      match '/' => 'index#index'

      match '/doctor/find' => 'doctor#find'
      match '/appointment/find' => 'appointment#find'
      match '/event/unsubscribe/:id' => 'event#unsubscribe'

      resources :calendar, :event, :doctor, :appointment, :parameter, :document
    end
    namespace :admin do
      root :to => 'index#index'
      match '/' => 'index#index'
    end
    namespace :manager do
      root :to => 'index#index'
      match '/' => 'index#index'

      resources :parameter, :bid, :event, :user, :rule_parameter_input

      match '/event/find' => 'event#find', :via => :post
      match '/event/find_attendee' => 'event#find_attendee', :via => :post
      match '/event/json' => 'event#json_format', :via => :post

      match '/rule/new' => 'recurrence#new', :via => :get
      match '/rule/find' => 'recurrence#find', :via => :post
      match '/rule/edit/:id' => 'recurrence#edit', :via => :get

      match '/user/find' => 'user#find', :via => :post
    end
  end

  scope :diagnostic do
    match '/parameter' => 'diagnostic#parameter', :via => :post
  end

  match ':controller(/:action(/:id))(.:format)'

  if ::Rails.application.config.handle_errors
    match '*path', :to => redirect { |params, request| "/error/404?from=#{request.url}" }
  end
end

app/models/patient.rb
class Patient < User
  default_scope :joins => :roles
  default_scope where("roles.name = 'patient'")
  default_scope :readonly => false
end

app/controllers/cabinet/admin/index_controller.rb
class Cabinet::Admin::IndexController < Cabinet::AdminController

  def index
  end

end

app/controllers/cabinet/admin_controller.rb
class Cabinet::AdminController < ApplicationController
  layout 'cabinet/admin/layout'

  before_filter :_authorize

  private
  def _authorize
    authorize! :access, :admin_cabinet
  end
end

app/controllers/cabinet/doctor/appointment_controller.rb
# encoding: UTF-8
class Cabinet::Doctor::AppointmentController < Cabinet::DoctorController

  layout 'cabinet/doctor/layout'

  #get appointment index page (search and select patient)
  def index
    #respond_to { |f|
    #  @appntEvents = DoctorUser.current.appointment_events.order("date_start DESC")
    #
    #  f.json {
    #    render :json => @appntEvents.to_json
    #  }
    #  f.html {}
    #}

    @appntEvents = DoctorUser.current.appointment_events.where('events.status <> ?', 'free').order("date_start DESC")
  end

  def get_free_appointments_for
    @doctor_id = params[:id] == "me" ? User.current.id : params[:id]
    @appntEvents = DoctorUser.find(@doctor_id).appointment_events.where('events.status = \'free\'').order('events.date_start DESC')

    @appntEvents.map!{|a|
      a.date_start = a.date_start.strftime('%d.%m.%Y %H:%M:%S')
      a
    }

    respond_to{|f|
      f.html { render :layout => false }
      f.json { render :json => @appntEvents.to_json }
    }
  end

  def confirm
    @appointment_id = params['apptId']
    @patientId = params['patId']

    @new_Attendee = PatientAttendee.new
    @new_Attendee.user_id=@patientId
    @new_Attendee.event_id=@appointment_id

    @new_Attendee.save!
    render :text => "Статус события изменен на #{@new_Attendee.event.status}"
  end

  #get form create appointments event
  def new
    @event = AppointmentEvent.new
  end

  def new_appointment
    respond_to do |f|
      f.html {
      }
    end
  end

  def get_patient_searching_form

  end

  #It return patients searching form for appointment setting
  def searching_form_for_appt_assig

  end

  #create new appontment
  def create
    @event = AppointmentEvent.new params[:appointment_event]

    raise 'Not @event object' if @event.nil?

    respond_to do |f|


      raise "There'nt patient_id" if params['patient_id'].blank?

      #Getting appointment which collision with new app-t
      app_nts_by_date_start = DoctorUser.current.appointment_events.where(:date_start => (@event.date_start)..(@event.date_end))
      app_nts_by_date_end = DoctorUser.current.appointment_events.where(:date_end => (@event.date_start)..(@event.date_end))

      if app_nts_by_date_end.count > 0 or app_nts_by_date_start.count > 0
        raise 'Incorrect appointment duration'
      end

      @event.user = DoctorUser.current
      @event.save!

      @at_doctor = AttendingDoctorAttendee.create({:user => DoctorUser.current, :event => @event})

      @at_patient = PatientAttendee.create({:user => PatientUser.find(params['patient_id']), :event => @event})

      @at_doctor.save
      @at_patient.save

      f.html do
        redirect_to :controller => 'cabinet/doctor/appointment', :action => 'index'
      end

      f.json do
        render text: 'The Appointment was created successfully', layout: false
      end
    end
  end

  #show appointment
  def show
    #Get appointment
    @a = AppointmentEvent.find_by_id(params[:id]) if params[:id].present?
    unless @a.present? then
      flash[:error] = 'Cannot appointment for this id'
      redirect_to cabinet_doctor_appointments_path()
    end
  end

  def start_appointment
    respond_to {|f|
      f.json{
        AppointmentEvent.find(params[:id]).start_appointment
        render text: "Прием ##{params[:id]} успешно начан".to_json, layout: false
      }
    }
  end

  def stop_appointment
    respond_to do |f|
      f.json do
        AppointmentEvent.find(params[:id]).finish_appointment
        render text: "Прием ##{params[:id]} успешно завершен".to_json, layout: false
      end
    end
  end
end

app/controllers/cabinet/doctor/diagnostic_controller.rb
class Cabinet::Doctor::DiagnosticController < Cabinet::DoctorController
  def show
    @patient = PatientUser.find(params[:id])
  end

  def chart
    from = Time.at(params[:from].to_i)
    to = Time.at(params[:to].to_i)

    respond_to do |f|
      f.json { render json: ChartFactory.build(params[:patient_id], params[:parameter_id], from, to) }
    end
  end

  def raw
    from = Time.at(params[:from].to_i)
    to = Time.at(params[:to].to_i)
    @data = DiagnosticFactory.raw(params[:patient_id], params[:parameter_id], from, to)
  end
end

app/controllers/cabinet/doctor/document_controller.rb
# encoding=UTF-8
class Cabinet::Doctor::DocumentController < ApplicationController

  layout 'cabinet/doctor/layout'

  #Creating new document
  def create

    respond_to { |f|
      begin
        @appointment_document = AppointmentDocument.new(:event_id => params[:event_id])
        @appointment_document.appointment_document_info = AppointmentDocumentInfo.new params[:appointment_document_info]

        @appointment_document.save!

        flash[:notice] = "Document was succefly cretating"
        return redirect_to cabinet_doctor_document_path(@appointment_document.id)
      rescue Exception => exp
        flash[:error] = exp.message
        return redirect_to new_cabinet_doctor_document_path(event_id: params[:event_id])
      end
    }
  end

  #
  #Here we introduce the default action for the Rails resource
  #create, new, edit, show, update, destroy
  #

  def index
  end

  #Get form for creating new document
  def new
    @adoc = AppointmentDocument.new(event_id: params[:event_id])
    @adoc.appointment_document_info = AppointmentDocumentInfo.new
  end

  def edit
  end

  def show

    #Get the document by id
    @doc = AppointmentDocument.where("id = ? AND user_id = ?", params[:id], User.current.id).first()

    respond_to do |f|
      f.html do
        unless @doc.present? then
          flash[:error] = "requst document was not found or your  access denied"
          redirect_to cabinet_doctor_documents_path()
        end
      end
    end
  end

  def update
  end

  def destroy
  end

  def get_form_body
    #Вставляем заглушку
    if params[:id] == '-1'
      @is_stub = true
    end
  end

end

app/controllers/cabinet/doctor/index_controller.rb
class Cabinet::Doctor::IndexController < Cabinet::DoctorController

  def index
  end

end

app/controllers/cabinet/doctor/parameter_controller.rb
class Cabinet::Doctor::ParameterController < Cabinet::DoctorController
  def link
    l = ParametersToPatients.new({:user_id => params[:patient_id], :parameter_id => params[:parameter_id]})
    respond_to do |f|
      if l.save
        f.json { render :json => {
            :message => 'parameter.link'
        } }
      else
        f.json { render :json => {
            :message => 'parameter.link.error',
            :errors => l.errors.messages
        }, :status => :unprocessable_entity }
      end
    end
  end

  def unlink
    l = ParametersToPatients.where(:user_id => params[:patient_id]).where(:parameter_id => params[:parameter_id]).first
    respond_to do |f|
      if l.destroy.destroyed?
        f.json { render :json => {
            :message => 'parameter.unlink'
        } }
      else
        f.json { render :json => {
            :message => 'parameter.unlink.error',
            :errors => l.errors.messages
        }, :status => :unprocessable_entity }
      end
    end
  end

end

app/controllers/cabinet/doctor/patient_controller.rb
# encoding: UTF-8
class Cabinet::Doctor::PatientController < Cabinet::DoctorController
  layout 'cabinet/doctor/layout'

  def index
    @patients = current_user.patient_users
    respond_to do |f|
      f.html {} # нужно чтобы html страничку отдавало при прямом переходе
      f.json {
        render :json => @patients.to_json
      }
    end
  end

  def show
    @patient = PatientUser.find params[:id]
  end

  def new
    respond_to { |f|
      f.html {}
    }
  end

  def all_diagnoses
    respond_to { |f|
      f.html {

      }

      f.json {
        render text: 'that is working', layout: false
      }
    }
  end

  def diagnoses_assigning
    @diagnoses = PatientUser.find(params[:id]).diagnosis
    respond_to { |f|
      f.html {}
    }
  end

  def find_diagnose
    respond_to { |f|
      f.html {
        @diagnoses = Diagnosis.custom_find_by_name(params[:name])
      }
    }

  end

  def confirm_diagnoses
    respond_to { |f|
      checkboxes = params[:item]

      diagnosis = PatientUser.find(params[:patient_id]).diagnosis

      if diagnosis.count > 0
        diagnosis.each { |diagnose|
          if checkboxes.present? && checkboxes.include?(diagnose.id)
            #If patient stay still with this diagnose
            checkboxes.reject! { |chbx| chbx == diagnose.id }
          else
            #If doctor unchecked this diagnose
            deleted = PatientToDiagnoses.where('user_id = ? AND diagnosis_id = ?', params[:patient_id], diagnose.id).first
            deleted.delete
          end
        }
      end

      if checkboxes.present?
        checkboxes.each { |i|
          new_patient_to_diagnose = PatientToDiagnoses.new
          new_patient_to_diagnose.user_id = params[:patient_id]
          new_patient_to_diagnose.diagnosis_id = i

          new_patient_to_diagnose.save
        }
      end

      f.html {render text: 'Диагнозы успешно обновлены'}
      f.json {
        render text: 'Диагнозы успешно обновлены', layout: false
      }
    }
  end

  def find_medicament
    respond_to { |f|
      f.html {
        @medicaments = Medicament.custom_find_by_name(params[:name])
      }
    }
  end

  def confirm_medicaments
    respond_to {|f|
      f.html {
        checkboxes = params[:item]
        medicaments = PatientUser.find(params[:patient_id]).medicaments

        if medicaments.count > 0
          medicaments.each { |medicament|
            if checkboxes.present? && checkboxes.include?(medicament.id)
              #If patient stay still with this medicament
              checkboxes.reject! { |chbx| chbx == medicament.id }
            else
              #If doctor unchecked this medicament
              deleted = PatientToMedicaments.where('users_id = ? AND medicaments_id = ?', params[:patient_id], medicament.id).first
              deleted.delete
            end
          }
        end

        if checkboxes.present?
          checkboxes.each { |i|
            new_patient_to_medicaments = PatientToMedicaments.new
            new_patient_to_medicaments.users_id = params[:patient_id]
            new_patient_to_medicaments.medicaments_id = i

            new_patient_to_medicaments.save
          }
        end

        render text: 'Медикаменты успешно назначены', layout: false
      }

      f.json{

      }
    }
  end
end

app/controllers/cabinet/doctor/user_controller.rb
class Cabinet::Doctor::UserController < ApplicationController
  
  layout 'cabinet/doctor/layout'
  
  #find user by name
  def find
    @users = User.searh_patients_by_email params[:name]
    respond_to do |f|
      f.html { render :layout => false }
      f.json { render :json => @users.to_json }
    end
  end

  def find_for_set
    @users = User.searh_patients_by_email params[:name]
    respond_to do |f|
      f.html { render :layout => false }
      f.json { render :json => @users.to_json }
    end
  end
  
  #find doctor
  def find_doctor
    @users = User.searh_doctors_by_email params[:name]
    respond_to do |f|
      f.html { render :layout => false }
      f.json { render :json => @users }
    end
  end

  def index
  
  end

  def get_doctors
    respond_to{|f|
      f.html { render :layout => false }
      f.json { render :json => DoctorUser.select("users.id, first_name, last_name").where("users.id <> ?", User.current.id).to_json }
    }
  end
end

app/controllers/cabinet/doctor_controller.rb
class Cabinet::DoctorController < ApplicationController
  layout 'cabinet/doctor/layout'

  before_filter :_authorize

  private
  def _authorize
    authorize! :access, :doctor_cabinet
  end
end

app/controllers/cabinet/manager/bid_controller.rb
class Cabinet::Manager::BidController < Cabinet::ManagerController
  layout 'cabinet/manager/layout'

  def index
    @bids = Bid.limit(20)
  end

  def show
    @bid = Bid.find params[:id]
  end

  def approve
    @bid = Bid.find params[:id]

    respond_to do |f|
      if @bid.approve
        f.html { redirect_to({:action => :show, :id => @bid.id}, :notice => 'bid_approved') }
      else
        raise Exception
      end
    end
  end

  def reject
    @bid = Bid.find params[:id]

    respond_to do |f|
      if @bid.reject
        f.html { redirect_to({:action => :show, :id => @bid.id}, :notice => 'bid_rejected') }
      else
        raise Exception
      end
    end
  end
end

app/controllers/cabinet/manager/calendar_controller.rb
class Cabinet::Manager::CalendarController < Cabinet::ManagerController
  layout 'cabinet/manager/layout'

  def index
  end

  def show
    @user = User.find params[:id]
    gon.id = params[:id]
  end
end

app/controllers/cabinet/manager/index_controller.rb
class Cabinet::Manager::IndexController < Cabinet::ManagerController

  def index
  end

end

app/controllers/cabinet/manager/rule_parameter_input_controller.rb
class Cabinet::Manager::RuleParameterInputController < Cabinet::ManagerController
  def index
    @rules = RuleParameterInput.all
  end
end

app/views/layouts/cabinet/patient/doctor.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shm" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body data-controller="<%= params[:controller] %>" data-action="<%= params[:action] %>">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= url_for cabinet_patient_path %>"><span>Кабинет пациента</span></a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="content">
        <div class="row-fluid">
          <div id="content">

          </div>
        </div><!--/row-->
      </div><!--/content-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= include_gon %>
    <script data-main="/assets/cabinet/patient/app" src="/assets/require.js"></script>

  </body>
</html>

app/views/layouts/cabinet/patient/layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- start: Meta -->
  <meta charset="utf-8">
  <title>Shm</title>
  <%= csrf_meta_tags %>
  <!-- end: Meta -->

  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end: Mobile Specific -->

  <!-- start: CSS -->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <!--<link id="base-style" href="/assets/style.css" rel="stylesheet">-->
  <!--<link id="base-style-responsive" href="css/style-responsive.css" rel="stylesheet">-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
  <!-- end: CSS -->

  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <%= stylesheet_link_tag 'ie' %>
  <![endif]-->

  <!--[if IE 9]>
    <%= stylesheet_link_tag 'ie9' %>
  <![endif]-->
</head>

<body>
<!-- start: Header -->
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= url_for cabinet_patient_path %>"><span>Кабинет пациента</span></a>

      <!-- start: Header Menu -->
      <div class="nav-no-collapse header-nav">
        <ul class="nav pull-right">
          <!-- start: User Dropdown -->
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <%= current_user.shortname %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#"><i class="icon-user"></i> Profile</a></li>
              <li><%= link_to 'Выход', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
          <!-- end: User Dropdown -->
        </ul>
      </div>
      <!-- end: Header Menu -->

    </div>
  </div>
</div>
<!-- start: Header -->

<div class="container-fluid">
  <div class="row-fluid">

    <!-- start: Main Menu -->
    <div id="sidebar-left" class="span1">
      <div class="nav-collapse sidebar-nav">
        <ul class="nav nav-tabs nav-stacked main-menu" id="menu">
          <li>
            <a href="<%= url_for cabinet_patient_path %>" data-view="index">
              <i class="icon-home"></i>
              <span class="hidden-tablet">Домашняя</span>
            </a>
          </li>
          <li>
            <a href="<%= url_for cabinet_patient_calendar_index_path %>" data-view="calendar">
              <i class="icon-calendar"></i>
              <span class="hidden-tablet">Календарь</span>
            </a>
          </li>
          <li>
            <a href="<%= url_for cabinet_patient_appointment_index_path %>" data-view="appointment">
              <i class="icon-file-alt"></i>
              <span class="hidden-tablet">Запись</span>
            </a>
          </li>
          <li>
            <a href="<%= url_for cabinet_patient_parameter_index_path %>" data-view="parameter">
              <i class="icon-tasks"></i>
              <span class="hidden-tablet">Параметры</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <!-- end: Main Menu -->

    <noscript>
      <div class="alert alert-block span11">
        <h4 class="alert-heading">Warning!</h4>

        <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to
          use
          this site.</p>
      </div>
    </noscript>

    <!-- start: Content -->
    <div id="content" class="span11">
    </div>
    <!--/#content.span10-->
  </div>
  <!--/fluid-row-->

  <div class="modal hide fade" id="myModal">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3>Settings</h3>
    </div>
    <div class="modal-body">
      <p>Here settings can be configured...</p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <a href="#" class="btn btn-primary">Save changes</a>
    </div>
  </div>

  <div class="clearfix"></div>

  <!--<footer>-->
  <!--<p>-->
  <!--<span style="text-align:left;float:left">&copy; <a href="" target="_blank">creativeLabs</a> 2013</span>-->
  <!--<span class="hidden-phone" style="text-align:right;float:right">Powered by: <a href="#">Acme Dashboard</a></span>-->
  <!--</p>-->

  <!--</footer>-->

</div>
<!--/.fluid-container-->

<!-- start: JavaScript-->

<!--<script src="js/jquery-1.7.2.min.js"></script>-->
<!--<script src="js/jquery-ui-1.8.21.custom.min.js"></script>-->

<!--<script src="js/modernizr.js"></script>-->

<!--<script src="js/bootstrap.js"></script>-->

<!--<script src="js/jquery.cookie.js"></script>-->

<!--<script src='js/fullcalendar.min.js'></script>-->

<!--<script src='js/jquery.dataTables.min.js'></script>-->

<!--<script src="js/excanvas.js"></script>-->
<!--<script src="js/jquery.flot.js"></script>-->
<!--<script src="js/jquery.flot.pie.js"></script>-->
<!--<script src="js/jquery.flot.stack.js"></script>-->
<!--<script src="js/jquery.flot.resize.min.js"></script>-->

<!--<script src="js/jquery.chosen.min.js"></script>-->

<!--<script src="js/jquery.uniform.min.js"></script>-->

<!--<script src="js/jquery.cleditor.min.js"></script>-->

<!--<script src="js/jquery.noty.js"></script>-->

<!--<script src="js/jquery.elfinder.min.js"></script>-->

<!--<script src="js/jquery.raty.min.js"></script>-->

<!--<script src="js/jquery.iphone.toggle.js"></script>-->

<!--<script src="js/jquery.uploadify-3.1.min.js"></script>-->

<!--<script src="js/jquery.gritter.min.js"></script>-->

<!--<script src="js/jquery.imagesloaded.js"></script>-->

<!--<script src="js/jquery.masonry.min.js"></script>-->

<!--<script src="js/jquery.knob.modified.js"></script>-->

<!--<script src="js/jquery.sparkline.min.js"></script>-->

<!--<script src="js/counter.js"></script>-->

<!--<script src="js/retina.js"></script>-->

<!--<script src="js/custom.js"></script>-->
<!--&lt;!&ndash; end: JavaScript&ndash;&gt;-->
<%= include_gon %>
<script data-main="/assets/cabinet/patient/app" src="/assets/require.js"></script>

</body>
</html>